FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y python3 python3-pip

WORKDIR /app

COPY . .

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python3", "main.py"]

# docker build -t dotflow --file dockerfile.debian .
# docker run -t dotflow