FROM fedora:latest

RUN dnf install -y python3.12 && python3.12 -m ensurepip --upgrade

WORKDIR /app

COPY . .

RUN python3.12 -m pip install --no-cache-dir -r requirements.txt

CMD ["python3.12", "main.py"]

# docker build -t dotflow --file dockerfile.fedora .
# docker run -t dotflow