FROM python:3.12-alpine

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]

# docker build -t dotflow --file dockerfile.alpine .
# docker run -t dotflow